name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./script/test
    - name: Publish
      if: ${{ success() && (github.ref == 'refs/heads/main') }}
      env:
        CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: |
        cargo login $CARGO_TOKEN
        cargo publish
